import {
  UtensilsCrossed, ShoppingCart, Laptop, Shirt, Home, Pill, BookOpen,
  Car, Dumbbell, Baby, Gem, Palette, Music, Camera, Gamepad2,
  Flower2, Dog, Watch, Glasses, Briefcase, Hammer, Bike, Plane,
  Coffee, Cake, Fish, Beef, Apple, Carrot, Milk,
  Smartphone, Headphones, Monitor, Printer, Cpu,
  Sofa, Lamp, Bath, BedDouble, CookingPot,
  Scissors, Footprints, Crown,
  PenTool, Wrench, Plug, Fan, TreePine, Tent, Mountain,
  Leaf, Globe, Heart, Sparkles, LucideIcon
} from "lucide-react";

export interface Category {
  id: string;
  name: string;
  icon: LucideIcon;
}

export const CATEGORIES: Category[] = [
  { id: "restaurant", name: "Restaurant", icon: UtensilsCrossed },
  { id: "food", name: "Food & Snacks", icon: Cake },
  { id: "grocery", name: "Grocery", icon: ShoppingCart },
  { id: "tech", name: "Technology", icon: Laptop },
  { id: "clothing", name: "Clothing & Fashion", icon: Shirt },
  { id: "home-decor", name: "Home & Décor", icon: Home },
  { id: "pharmacy", name: "Pharmacy & Health", icon: Pill },
  { id: "books", name: "Books & Stationery", icon: BookOpen },
  { id: "automotive", name: "Automotive", icon: Car },
  { id: "fitness", name: "Fitness & Sports", icon: Dumbbell },
  { id: "baby", name: "Baby & Kids", icon: Baby },
  { id: "jewelry", name: "Jewelry & Accessories", icon: Gem },
  { id: "art", name: "Art & Crafts", icon: Palette },
  { id: "music", name: "Musical Instruments", icon: Music },
  { id: "photography", name: "Photography", icon: Camera },
  { id: "gaming", name: "Gaming", icon: Gamepad2 },
  { id: "flowers", name: "Flowers & Gifts", icon: Flower2 },
  { id: "pets", name: "Pet Supplies", icon: Dog },
  { id: "watches", name: "Watches", icon: Watch },
  { id: "eyewear", name: "Eyewear", icon: Glasses },
  { id: "office", name: "Office Supplies", icon: Briefcase },
  { id: "hardware", name: "Hardware & Tools", icon: Hammer },
  { id: "bicycles", name: "Bicycles", icon: Bike },
  { id: "travel", name: "Travel & Luggage", icon: Plane },
  { id: "coffee-tea", name: "Coffee & Tea", icon: Coffee },
  { id: "seafood", name: "Seafood", icon: Fish },
  { id: "meat", name: "Meat & Poultry", icon: Beef },
  { id: "fruits", name: "Fruits", icon: Apple },
  { id: "vegetables", name: "Vegetables", icon: Carrot },
  { id: "dairy", name: "Dairy Products", icon: Milk },
  { id: "smartphones", name: "Smartphones", icon: Smartphone },
  { id: "audio", name: "Audio & Headphones", icon: Headphones },
  { id: "computers", name: "Computers & Monitors", icon: Monitor },
  { id: "printers", name: "Printers & Scanners", icon: Printer },
  { id: "components", name: "PC Components", icon: Cpu },
  { id: "furniture", name: "Furniture", icon: Sofa },
  { id: "lighting", name: "Lighting", icon: Lamp },
  { id: "bathroom", name: "Bathroom", icon: Bath },
  { id: "bedroom", name: "Bedroom", icon: BedDouble },
  { id: "kitchen", name: "Kitchen Appliances", icon: CookingPot },
  { id: "salon", name: "Salon & Beauty", icon: Scissors },
  { id: "footwear", name: "Footwear", icon: Footprints },
  { id: "luxury", name: "Luxury Goods", icon: Crown },
  { id: "design", name: "Design Services", icon: PenTool },
  { id: "repair", name: "Repair Services", icon: Wrench },
  { id: "electronics", name: "Electronics", icon: Plug },
  { id: "appliances", name: "Home Appliances", icon: Fan },
  { id: "garden", name: "Garden & Plants", icon: TreePine },
  { id: "camping", name: "Camping & Outdoor", icon: Tent },
  { id: "adventure", name: "Adventure Gear", icon: Mountain },
  { id: "organic", name: "Organic Products", icon: Leaf },
  { id: "international", name: "International Goods", icon: Globe },
  { id: "wellness", name: "Wellness & Spa", icon: Heart },
  { id: "handmade", name: "Handmade & Custom", icon: Sparkles },
];
